#seqinr - R package to generate dot plots.
#dotPlot(a, b)
#dotplot - R package to rapidly generate dot plots as either traditional or ggplot graphics.

# INPUT LINES
a <- "IPEYVDWRQKGAVTPVKNQGSCGSCWAFSAVVTIEGIIKIRTGNLNQYSEQELLDCD1RRSYGCNGGYPWSALQLVAQYG"
b <- "APRSVDWREKGYVTPVKNQGQCGSCWAFSATGALEGQMFRKTGRLISLSEQNLVDCSGPQGNEGCNGGLMDYAFQYVQDNG"
#a <- "DOROTHYCROWFOOTHODGKIN"
#b <- "DOROTHYHODGKIN"

# FUNCTION TO SPLIT A STRING INTO A VECTOR OF N CHARACTERS
splitN <- function(x, n) {
  substring(x, # GRAB A STRING AND SPLIT IT INTO N CHARACTERS...
            seq(1,nchar(x),n), # FROM THIS INDEXES
            seq(n,nchar(x),n) #  TO THIS INDEXES
  ) 
}

# CREATE A VECTOR OF CHARACTERS FROM TH INPUTS
a <- splitN(a, 1) # SPLIT A INTO A VECTOR OF 1 CHARACTER
b <- splitN(b, 1) # SPLIT B INTO A VECTOR OF 1 CHARACTER
b <- rev(b) # REVERSE ONE OF THE INPUTS

r <- list()
# FOR EACH CHARACTER IN B
for (i in 1:length(b)) {
  r[[i]] <- a==b[i] # CREATE A LOGICAL VECTOR TESTING FOR THE PRESENCE OF THE CHARACTER IN B in A AND ADD IT TO A LIST
}

m <- matrix( # CREATE A MATRIX
        as.numeric(unlist(r)), # USING THE LIST OF LOGICAL VECTORS AS A SINGLE VECTOR
        nrow = length(b),  # WITH AS MANY ROWS AS CHARACTERS IN VECTOR B
        byrow = TRUE,  # FILL IN BY ROWS INSTEAD OF BY COLUMNS
        dimnames = list(b,a) # NAME EACH ROW AS EACH CHARACTER IN VECTOR B AND EACH COLUMN AS EACH CHARACTER IN VECTOR A
)

par(pty = "s") # MAKE A SQUARE GRAPHIC
image( # CREATE A DOTPLOT BY COLORING THE PIXELS
  t(m),  # ACCORDING TO THE LOGICAL VALUES ON THE MATRIX
  col = c("white", "black"), # 0 REPRESENTS A WHITE PIXEL AND 1 REPRESENTS A BLACK PIXEL
  xaxt = "n", # GET RID OF THE X AXIS
  yaxt = "n" # GET RID OF THE Y AXI
) 
box() # PUT A BORDER AROUND THE PLOT
axis(side = 3, # CREATE AN AXIS ON THE TOP SIDE OF THE PLOT
     at= seq(0,1, length.out = ncol(m)),  # AT EVERY PIXEL CORRESPONDING TO THE NUMBER OF CHARACTERS IN VECTOR A
     labels = colnames(m), # PUT LABELS ON THE AXIS EQUAL TO EACH CHARACTER IN VECTOR A
     cex.axis = 0.4, # SET THE SIZE OF THE LABELS
     tck = 0 # ELIMINATE TICKS
)
axis(side = 2, # CREATE AN AXIS ON THE LEFT SIDE OF THE PLOT
     at= seq(0,1, length.out = nrow(m)), # AT EVERY PIXEL CORRESPONDING TO THE NUMBER OF CHARACTERS IN VECTOR B
     labels = rownames(m), # PUT LABELS ON THE AXIS EQUAL TO EACH CHARACTER IN VECTOR B
     cex.axis = 0.4, # SET THE SIZE OF THE LABELS
     tck = 0 # ELIMINATE TICKS
)