#seqinr - R package to generate dot plots.
#dotPlot(a, b)
#dotplot - R package to rapidly generate dot plots as either traditional or ggplot graphics.

a <- "IPEYVDWRQKGAVTPVKNQGSCGSCWAFSAVVTIEGIIKIRTGNLNQYSEQELLDCDRRSYGCNGGYPWSALQLVAQYG"
b <- "APRSVDWREKGYVTPVKNQGQCGSCWAFSATGALEGQMFRKTGRLISLSEQNLVDCSGPQGNEGCNGGLMDYAFQYVQDNG"
#a <- "DOROTHYCROWFOOTHODGKIN"
# <- "DOROTHYHODGKIN"

splitN <- function(x, n) {
  substring(x,seq(1,nchar(x),n),seq(n,nchar(x),n)) 
}

a <- splitN(a, 1)
b <- splitN(b, 1)
b <- rev(b)

r <- list()

for (i in 1:length(b)) {
  r[[i]] <- a==b[i]
}

m <- matrix(as.numeric(unlist(r)), nrow = length(b), byrow = TRUE, dimnames = list(b,a))

#METHOD 1
par(pty = "s")
image(t(m), col = c("white", "black"), xaxt = "n", yaxt = "n")
#grid(ncol(m), nrow(m), "black")
box()
axis(side = 3, at= seq(0,1, length.out = ncol(m)), 
     labels = colnames(m), cex.axis = 0.4, tck = 0)
axis(side = 2, at= seq(0,1, length.out = nrow(m)), 
     labels = rownames(m), cex.axis = 0.4, tck = 0, las = 2)

#METHOD 2
heatmap(m, Rowv = NA, Colv = NA)

#METHOD 3
d1 <- c()
d2 <- c()
rownames(m)
for (i in 1:nrow(m)) {
  for (j in 1:ncol(m)) {
    if (m[i,j] == 1) {
      d1 <- c(d1, j)
      d2 <- c(d2, i)
    }
  }
}

plot(d1, d2, xaxt = "n", yaxt = "n")
axis(3, at= 1:ncol(m), labels = colnames(m), cex.axis = 0.7, tck = 0)
axis(2, at= 1:nrow(m), labels = rownames(m), cex.axis = 0.7, tck = 0, las = 2)
#grid(ncol(m), nrow(m), "black")


# ATPases lamprey / dogfish                  #TITLE
# 15 6                                       #WINDOW, THRESHOLD
# Petromyzon marinus mitochondrion           #SEQUENCE 1
# ATGACACTAGATATCTTTGACCAATTTACCTCCCCAACA
# ATATTTGGGCTTCCACTAGCCTGATTAGCTATACTAGCCCCTAGCTTA
# ATATTAGTTTCACAAACACCAAAATTTATCAAATCTCGTTATCACACACTA
# CTTACACCCATCTTAACATCTATTGCCAAACAACTCTTTCTTCCAATAAAC
# CAACAAGGGCATAAATGAGCCTTAATTTGTATAGCCTCTATAATATTTATC
# TTAATAATTAATCTTTTAGGATTATTACCATATACTTATACACCAACTACC
# CAATTATCAATAAACATAGGATTAGCAGTGCCACTATGACTAGCTACTGTC
# CTCATTGGGTTACAAAAAAAACCAACAGAAGCCCTAGCCCACTTATTACCA
# GAAGGTACCCCAGCAGCACTCATTCCCATATTAATTATCATTGAAACTATT
# AGTCTTTTTATCCGACCTATCGCCCTAGGAGTCCGACTAACCGCTAATTTA
# ACAGCTGGTCACTTACTTATACAACTAGTTTCTATAACAACCTTTGTAATA
# ATTCCTGTCATTTCAATTTCAATTATTACCTCACTACTTCTTCTATTA
# CTAACAATTCTGGAGTTAGCTGTTGCTGTAATCCAGGCATATGTATTTATT
# CTACTTTTAACTCTTTATCTGCAAGAAAACGTTT*    
#   Scyliorhinus canicula mitochondrion         #SEQUENCE 2
# ATGATTATAAGCTTTTTTGATCAATTCCTAAGTCCCTCCTTTCTAGGA
# ATCCCACTAATTGCCCTAGCTATTTCAATTCCATGATTAATATTTCCAACACCAACC
# AATCGTTGACTTAATAATCGATTATTAACTCTTCAAGCATGATTTATTAACCGATTTATT
# TATCAACTAATACAACCCATAAATTTAGGAGGACATAAATGAGCTATCTTATTTACAGCC
# CTAATATTATTTTTAATTACCATCAATCTTCTAGGTCTCCTTCCATATACTTTTACGCCT
# ACAACTCAACTTTCTCTTAATATAGCCTTTGCCCTGCCCTTATGGCTTACAACTGTATTA
# ATTGGTATATTTAATCAACCAACCATTGCCCTAGGGCACTTATTACCTGAAGGTACCCCA
# ACCCCTTTAGTACCAGTACTAATCATTATCGAAACCATCAGTTTATTTATTCGACCATTA
# GCCTTAGGAGTCCGATTAACAGCCAACTTAACAGCTGGACATCTCCTTATACAATTAATC
# GCAACTGCGGCCTTTGTCCTTTTAACTATAATACCAACCGTGGCCTTACTAACCTCCCTA
# GTCCTGTTCCTATTGACTATTTTAGAAGTGGCTGTAGCTATAATTCAAGCATACGTATTT
# GTCCTTCTTTTAAGCTTATATCTACAAGAAAACGTATAA*